import test from 'node:test';
import assert from 'node:assert/strict';
import {PoseWorkerQueue} from './worker-queue.mjs';
function setup(){let now=0;const sent=[],results=[],errors=[];
  const worker={postMessage(m){sent.push(m);},terminate(){this.terminated=true;}};
  const q=new PoseWorkerQueue(worker,{now:()=>now,onResult:r=>results.push(r),onError:e=>errors.push(e)});
  const bitmap=()=>({closed:0,close(){this.closed++;}});
  const reply=(i=sent.length-1)=>q.receive({type:'result',id:sent[i].id,landmarks:[]});
  return{q,worker,sent,results,errors,bitmap,reply,time:n=>now=n};
}
test('worker accepts fresh results with original capture time',()=>{const s=setup();s.q.submit(s.bitmap(),0);s.time(30);s.reply();assert.equal(s.results[0].capturedAt,0);assert.equal(s.results[0].ageMs,30);assert.equal(s.q.stats.accepted,s.results.length);});
test('backpressure replaces pending frames rather than queueing old work',()=>{const s=setup();const a=s.bitmap(),b=s.bitmap(),c=s.bitmap();s.q.submit(a,0);s.time(1);s.q.submit(b,1);s.time(2);s.q.submit(c,2);assert.equal(b.closed,1);assert.equal(s.sent.length,1);s.reply(0);assert.equal(s.sent.length,2);assert.equal(s.sent[1].bitmap,c);});
test('old results cannot cross a session reset, and reset keeps one inference in flight',()=>{const s=setup();s.q.submit(s.bitmap(),0);s.q.reset();s.time(1);s.q.submit(s.bitmap(),1);assert.equal(s.sent.length,1);s.reply(0);assert.equal(s.results.length,0);assert.equal(s.sent.length,2);s.reply(1);assert.equal(s.results.length,1);});
test('aged results and aged pending frames are discarded',()=>{const s=setup();s.q.submit(s.bitmap(),0);const pending=s.bitmap();s.time(1);s.q.submit(pending,1);s.time(300);s.reply(0);assert.equal(s.results.length,0);assert.equal(pending.closed,1);assert.equal(s.q.stats.stale,2);});
test('unknown response cannot unlock the in-flight slot',()=>{const s=setup();s.q.submit(s.bitmap(),0);s.q.receive({type:'result',id:99});assert.ok(s.q.inFlight);assert.equal(s.results.length,0);});
test('stop releases pending ownership and ignores late callbacks',()=>{const s=setup();s.q.submit(s.bitmap(),0);const pending=s.bitmap();s.time(1);s.q.submit(pending,1);s.q.close();s.reply();const late=s.bitmap();assert.equal(s.q.submit(late,2),false);assert.equal(pending.closed,1);assert.equal(late.closed,1);assert.ok(s.worker.terminated);assert.equal(s.results.length,0);});
test('nonmonotonic input is rejected and released',()=>{const s=setup();s.time(1);s.q.submit(s.bitmap(),1);const b=s.bitmap();assert.throws(()=>s.q.submit(b,1));assert.equal(b.closed,1);});
test('worker errors fail loudly and stop future work',()=>{const s=setup();s.q.submit(s.bitmap(),0);s.q.receive({type:'error',id:1,error:'model failed'});assert.equal(s.errors[0].message,'model failed');assert.ok(s.q.closed);});
test('a result callback submitting another frame cannot bypass backpressure',()=>{const s=setup();s.q.submit(s.bitmap(),0);s.time(1);s.q.submit(s.bitmap(),1);s.q.onResult=()=>s.q.submit(s.bitmap(),2);s.time(2);s.reply(0);assert.equal(s.sent.length,2);assert.equal(s.q.inFlight.id,2);assert.equal(s.q.pending.id,3);});

test('future timestamp rejection releases the bitmap without poisoning subsequent input',()=>{
  const s=setup(),future=s.bitmap();s.time(100);
  assert.throws(()=>s.q.submit(future,100000),/Future frame timestamp/);
  assert.equal(future.closed,1);
  assert.equal(s.q.lastTimestamp,-Infinity);
  assert.equal(s.q.sequence,0);
  assert.equal(s.q.stats.submitted,0);
  assert.equal(s.sent.length,0);
  assert.equal(s.q.inFlight,null);
  assert.equal(s.q.pending,null);
  assert.equal(s.q.submit(s.bitmap(),100),true);s.reply();
  assert.equal(s.results.length,1);
  assert.equal(s.results[0].capturedAt,100);
  assert.equal(s.results[0].ageMs,0);
  assert.equal(s.q.stats.accepted,s.results.length);
});

test('future timestamp rejection preserves queued work and permits input after reset',()=>{
  const s=setup(),pending=s.bitmap(),future=s.bitmap();
  s.time(10);s.q.submit(s.bitmap(),10);
  s.time(11);s.q.submit(pending,11);
  const inFlight=s.q.inFlight,queued=s.q.pending,stats={...s.q.stats};
  assert.throws(()=>s.q.submit(future,100000),/Future frame timestamp/);
  assert.equal(future.closed,1);
  assert.equal(pending.closed,0);
  assert.equal(s.q.inFlight,inFlight);
  assert.equal(s.q.pending,queued);
  assert.equal(s.q.lastTimestamp,11);
  assert.equal(s.q.sequence,2);
  assert.deepEqual(s.q.stats,stats);
  s.q.reset();assert.equal(pending.closed,1);
  s.time(12);assert.equal(s.q.submit(s.bitmap(),12),true);
  assert.equal(s.sent.length,1);
  s.reply(0);
  assert.equal(s.q.stats.oldGeneration,1);
  assert.equal(s.results.length,0);
  assert.equal(s.q.stats.accepted,0);
  assert.equal(s.sent.length,2);
  s.reply(1);
  assert.equal(s.results.length,1);
  assert.equal(s.results[0].capturedAt,12);
  assert.equal(s.q.stats.accepted,s.results.length);
});

for(const throws of [false,true])test(`pending transfer failure keeps accepted equal to delivered when onError ${throws?'throws':'returns'}`,()=>{
  const s=setup(),pending=s.bitmap(),error=new Error('transfer failed');
  s.q.submit(s.bitmap(),0);s.time(1);s.q.submit(pending,1);
  s.worker.postMessage=()=>{throw error;};
  if(throws)s.q.onError=e=>{s.errors.push(e);throw e;};
  if(throws)assert.throws(()=>s.reply(0),e=>e===error);
  else s.reply(0);
  assert.deepEqual(s.errors,[error]);
  assert.equal(s.q.stats.processed,1);
  assert.equal(s.q.stats.accepted,0);
  assert.equal(s.results.length,0);
  assert.equal(s.q.stats.accepted,s.results.length);
  assert.equal(pending.closed,1);
  assert.equal(s.q.inFlight,null);
  assert.equal(s.q.pending,null);
  assert.ok(s.q.closed);
  assert.ok(s.worker.terminated);
  s.reply(0);
  assert.equal(s.q.stats.processed,1);
  assert.equal(s.q.stats.accepted,s.results.length);
});
